name: frontend_admin
description: TSIMS Fronted Admin
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter_riverpod: ^2.0.0-dev.9
  http: ^0.13.4
  beamer: ^1.4.1+1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  flutter:
    sdk: flutter
  qr_flutter: ^4.0.0
  graphql: ^5.1.1
  gql: ^0.13.1
  jwt_decode: ^0.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true